### ISSUE TITLE
Erigon cannot unfold and require a full resync

### ISSUE THREAD

**Issue by Giulio2002** [erigontech/erigon#12230]
Logs say```[WARN] [10-06|13:00:22.791] [agg] lookupVisibleFileByItsRange: file not found stepFrom=1644 stepTo=1646 _visible=0-1024;1024-1536;1536-1600;1600-1632;1632-1648; visibleFilesCount=5 [CRIT] [10-06|13:00:22.791] storage file of steps 1644-1646 not found [INFO] [10-06|13:00:22.793] [4/6 Execution] Done blk=20906650 blks=4623 blk/s=23.2 txs=673824 tx/s=3.37k gas/s=351.05M buf=246.5MB/2.0GB stepsInDB=0.00 step=1648.5 alloc=23.0GB sys=31.1GB [WARN] [10-06|13:00:22.793] Cannot update chain head hash=0x0fddd6064705b54db0931d7e2b8c773c09c71e63205618494e007e8138cb8141 err="updateForkChoice: [4/6 Execution] StateV3.Apply: hash sort failed: loadIntoTable : unfold: Branch failed: storage file not found" [INFO] [10-06|13:00:58.055] State processing progress slot=6619549 blk/sec=15.52 [INFO] [10-06|13:00:59.434] P2P app=caplin peers=17 [INFO] [10-06|13:01:08.174] [3/6 Senders] Started from=20902027 to=20906671 [INFO] [10-06|13:01:09.072] cl reorg new_head_slot=10116303 fork_slot=10116282 old_canonical=0x02a3960fdd28e844bc969296191f1029792dc32897eda0b26141a5934d23e7e6 new_canonical=0xe1ade804b6240e0633edcfa46be35d2e491042e70712850ae3e27031b2057ab1 [INFO] [10-06|13:01:15.096] [4/6 Execution] starting from=20902028 to=20906671 fromTxNum=2575036576 offsetFromBlockBeginning=0 initialCycle=false useExternalTx=true```

And restart does not help

**Comment by d2x** [comment]
I'm seeing similar after upgrading the v3.0.0-alpha5 from alpha4

```
WARN[11-09|19:11:22.119] [agg] lookupVisibleFileByItsRange: file not found stepFrom=1660 stepTo=1662 _visible=0-1024;1024-1536;1536-1664;1664-1665; visibleFilesCount=4
WARN[11-09|19:11:22.119] visible account file of steps 1660-1662 not found
 
WARN[11-09|19:11:22.127] [agg] lookupVisibleFileByItsRange: file not found stepFrom=1656 stepTo=1660 _visible=0-1024;1024-1536;1536-1664;1664-1665; visibleFilesCount=4
WARN[11-09|19:11:22.127] visible storage file of steps 1656-1660 not found
 
WARN[11-09|19:11:22.127] [agg] lookupVisibleFileByItsRange: file not found stepFrom=1656 stepTo=1660 _visible=0-1024;1024-1536;1536-1664;1664-1665; visibleFilesCount=4
WARN[11-09|19:11:22.127] visible account file of steps 1656-1660 not found
 
WARN[11-09|19:11:22.138] [agg] lookupVisibleFileByItsRange: file not found stepFrom=1600 stepTo=1632 _visible=0-1024;1024-1536;1536-1664;1664-1665; visibleFilesCount=4
WARN[11-09|19:11:22.138] visible storage file of steps 1600-1632 not found
 
WARN[11-09|19:11:22.138] [agg] lookupVisibleFileByItsRange: file not found stepFrom=1600 stepTo=1632 _visible=0-1024;1024-1536;1536-1664;1664-1665; visibleFilesCount=4
WARN[11-09|19:11:22.138] visible account file of steps 1600-1632 not found
```

@Giulio2002 does https://github.com/erigontech/erigon/commit/7e6f9c49bfee228809e7807e81897e0d8b0c03ef resolve this issue?

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/erigontech/erigon/pull/12675

**Comment by d2x** [comment]
@AskAlexSharov this is still an issue, though https://github.com/erigontech/erigon/pull/12675 did remove the [agg] line and blank line. Current output is:

```
WARN[11-10|13:07:38.817] visible storage file of steps 1536-1600 not found 
WARN[11-10|13:07:38.817] visible account file of steps 1536-1600 not found 
WARN[11-10|13:07:38.821] visible storage file of steps 1600-1632 not found 
WARN[11-10|13:07:38.821] visible account file of steps 1600-1632 not found 
WARN[11-10|13:07:38.827] visible storage file of steps 1660-1662 not found 
WARN[11-10|13:07:38.827] visible account file of steps 1660-1662 not found 
WARN[11-10|13:07:38.827] visible storage file of steps 1536-1600 not found 
WARN[11-10|13:07:38.827] visible account file of steps 1536-1600 not found 
WARN[11-10|13:07:38.833] visible storage file of steps 1632-1648 not found 
WARN[11-10|13:07:38.833] visible account file of steps 1632-1648 not found 
WARN[11-10|13:07:38.834] visible storage file of steps 1600-1632 not found 
WARN[11-10|13:07:38.834] visible account file of steps 1600-1632 not found 
WARN[11-10|13:07:38.841] visible storage file of steps 1632-1648 not found 
WARN[11-10|13:07:38.841] visible account file of steps 1632-1648 not found 
WARN[11-10|13:07:38.843] visible storage file of steps 1536-1600 not found 
WARN[11-10|13:07:38.843] visible account file of steps 1536-1600 not found 
WARN[11-10|13:07:38.844] visible storage file of steps 1536-1600 not found 
WARN[11-10|13:07:38.844] visible account file of steps 1536-1600 not found 
WARN[11-10|13:07:38.848] visible storage file of steps 1656-1660 not found 
WARN[11-10|13:07:38.848] visible account file of steps 1656-1660 not found 
WARN[11-10|13:07:38.852] visible storage file of steps 1632-1648 not found 
WARN[11-10|13:07:38.852] visible account file of steps 1632-1648 not found 
WARN[11-10|13:07:38.853] visible storage file of steps 1600-1632 not found 
WARN[11-10|13:07:38.853] visible account file of steps 1600-1632 not found 
WARN[11-10|13:07:38.855] visible storage file of steps 1656-1660 not found 
WARN[11-10|13:07:38.855] visible account file of steps 1656-1660 not found 
WARN[11-10|13:07:38.856] visible storage file of steps 1536-1600 not found 
```
