### ISSUE TITLE
trace_block returns "insufficient funds for gas * price + value" error on block 21030627

### ISSUE THREAD

**Issue by quick-pawiromitchel** [erigontech/erigon#12525]
#### System information

Erigon version: `erigon/2.60.4/linux-amd64/go1.22.5`

OS & Version: Linux

Chain/Network: Mainnet

#### Steps to reproduce the behaviour
```
{
  "method": "trace_block",
  "params": [
    "0x140e6e3"
  ],
  "id": 1,
  "jsonrpc": "2.0"
}
```

Returns
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "first run for txIndex 85 error: insufficient funds for gas * price + value: address 0x0b92619DdE55C0cbf828d32993a7fB004E00c84B have 1414044108792614043 want 1414044806692614043"
  }
}
```

#### Backtrace

````
Oct 29 13:25:37 erigon[1105]: [WARN] [10-29|13:25:37.367] [rpc] served                             conn=xxxxx:59459 method=trace_block reqid=1 t=34.504079ms err="first run for txIndex 85 error: insufficient funds for gas * price + value: address 0x0b92619DdE55C0cbf828d32993a7fB004E00c84B have 1414044108792614043 want 1414044806692614043"
````

**Comment by yperbasis** [comment]
Fixed by PR #12559 and will be released in v2.60.10.

**Comment by Tommel71** [comment]
@yperbasis There seems to be something wrong, we still get the error on 2.60.10 with the newest docker container and the git_tag seems to be 2.60.9 still
```

○ → docker run erigontech/erigon:latest
[INFO] [11-06|14:44:41.097] logging to file system                   log dir=/home/erigon/.local/share/erigon/logs file prefix=erigon log level=info json=false
[INFO] [11-06|14:44:41.098] Build info                               git_branch=release/2.60 git_tag=v2.60.9-4-g3afee08bff git_commit=3afee08bfff043a731485e0a92dd8650823d8884
[INFO] [11-06|14:44:41.098] Starting Erigon on Ethereum mainnet...
```

**Comment by lystopad** [comment]
Hi, all

"git_tag" in this case is the output of `git describe --tags '--match=v*' --dirty` [see here](https://github.com/erigontech/erigon/blob/3afee08bfff043a731485e0a92dd8650823d8884/Makefile#L9C23-L9C63)

This outputs basically means -- the last tag found in git was "v2.60.9" and current git repository state is 4 commits on top of that tag and latest short commit id is "3afee08bff". [More details could be found here](https://git-scm.com/docs/git-describe).

It is done so, because we decided to TAG git repository after release.
Let me know if you would like to discuss/change it.

P.S.
In the following PR https://github.com/erigontech/erigon/pull/12658 I changed short commit id to be 7 chars which will match short commit IDs in github history (easy to find).

**Comment by Tommel71** [comment]
@yperbasis @lystopad

It is not just the tag but more importantly that the issue described in this thread persists.

**Comment by yperbasis** [comment]
@Tommel71 `trace_block` now works fine for 0x140e6e3 on my v2.60.10 node (albeit I built it locally instead of using the docker image).

**Comment by soad003** [comment]
@yperbasis for us (same team as @Tommel71), the issue persists after updating to the v2.60.10 docker image. 

The curl call returns an error as before. Do you have any advice, is there some cache we need to reset or could it be an issue with the docker image?

**Comment by tohadv** [comment]
Hi! I have the same error! I try to build erigon and rpcdaemon, try to use 2.60.10 v1 and v2 and still have it :(

**Comment by mdragaschnig** [comment]
> [..] Perhaps there's something wrong with the docker image.

That's possibly the case; using the official docker image 
```
erigontech/erigon                                     v2.60.10          sha256:87975922b4506b5e0956e8523a4638a63bbeeb01941bcfe5f82a55343d3c2846   c2ee3624690f   8 days ago      597MB
```

 produces
```
curl -X POST http://erigon2.60.10 -H 'Content-Type: application/json' -d '{"method":"trace_block","params":["0x140e6e3"],"id":1,"jsonrpc":"2.0"}'`
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"first run for txIndex 85 error: insufficient funds for gas * price + value: address 0x0b92619DdE55C0cbf828d32993a7fB004E00c84B have 1414044108792614043 want 1414044806692614043"}}
```

**Comment by yperbasis** [comment]
Sorry, I can't reproduce the issue and am out of ideas, so closing.

**Comment by 32ethers** [comment]
I have the same issue, my erigon version is ```erigon version 2.60.10-3afee08b```, chifra version is ```chifra version GHC-TrueBlocks//3.5.0-release```, but actually it is complied from the latest code in master branch, version should above 3.8

**Comment by mdragaschnig** [comment]
> Sorry, I can't reproduce the issue and am out of ideas, so closing.

Thanks for testing; so did the docker image version work for you?

I've just tried with the latest docker image [v2.61.0-beta](https://hub.docker.com/layers/erigontech/erigon/v2.61.0-beta1/images/sha256-12734df3179a8a02a684d97d7bfa381fb07b841e7315d827daede9f0d1696921?context=explore) 

```git_branch=release/2.61 git_tag=v2.61.0-beta1 git_commit=9dc3435f893801cbff5d2cec74f66ec97d4da74c```

and here the insufficient funds error still exists.

As @32ethers said; can the problem be that the database was written with a pre 2.60.10 version?

**Comment by yperbasis** [comment]
> Thanks for testing; so did the docker image version work for you?
> 
> I've just tried with the latest docker image [v2.61.0-beta](https://hub.docker.com/layers/erigontech/erigon/v2.61.0-beta1/images/sha256-12734df3179a8a02a684d97d7bfa381fb07b841e7315d827daede9f0d1696921?context=explore)
> 
> `git_branch=release/2.61 git_tag=v2.61.0-beta1 git_commit=9dc3435f893801cbff5d2cec74f66ec97d4da74c`
> 
> and here the insufficient funds error still exists.
> 
> As @32ethers said; can the problem be that the database was written with a pre 2.60.10 version?

No, this is a pure code change, not related to the database. That's why I'm a bit lost why v2.60.10 or v2.61.0-beta aren't working for you.

**Comment by yperbasis** [comment]
@32ethers yes, you need to update `rpcdaemon` to v2.60.10 as well.

**Comment by 32ethers** [comment]
I remove source code and compile again, and switch to 2.61.0 tag, still not work. here is what i did: 

```sh
rm -rf erigon
git clone https://github.com/erigontech/erigon.git
cd erigon
make
build/bin/erigon --version # ensure version is 2.61
cp -r build/bin /node1/erigon_2.61.0-beta1
cd /node1/erigon_2.61.0-beta1
./rpcdaemon --datadir="/node1/eth/"  --txpool.api.addr=localhost:9070  --private.api.addr=localhost:9070  --http.addr=0.0.0.0 --http.api=eth,erigon,web3,net,debug,trace,txpool
```

And still got the error, rpcdaemon will give a warning, and chifra will raise a error ant read that height repeatly. 

![image](https://github.com/user-attachments/assets/37ae33db-aef5-451a-8b5c-673a5800c169)


Did I miss something? Do I have some cache to clean elsewhere?

**Comment by 32ethers** [comment]
Hi @yperbasis 

I tested again, turn out if you use rpc in erigon, it will work, but **rpcdaemon** doesn't. 

so you should consider fix rpcdaemon as well.

**Comment by yperbasis** [comment]
The remote rpcdaemon case is fixed by PR #13125/#13128/#13129
