### ISSUE TITLE
eth_getTransactionReceipt error - seek with txNum=6850 but data before txNum=118750000 is not available

### ISSUE THREAD

**Issue by darinvhs** [erigontech/erigon#14203]
#### System information

Erigon version: erigon version 3.00.0-rc3-844c6cf3

OS & Version: Linux

Commit hash: https://github.com/erigontech/erigon/releases/tag/v3.0.0-rc3

Erigon Command (with flags/config):
```
        - erigon
        - --chain=holesky
        - --datadir=/home/erigon/persistence/data
        - --http.addr=0.0.0.0
        - --rpc.accessList=/home/erigon/acl-config/acl.json
        - --rpc.batch.limit=1000
        - --rpc.txfeecap=100
        - --http.api=eth,erigon,web3,net,debug,txpool,trace
        - --http.vhosts=*
        - --http.corsdomain=null
        - --http
        - --ws
        - --db.pagesize=4096
        - --ethash.dagdir=/home/erigon/persistence/dag
        - --maxpeers=100
        - --identity=xxx-xxx-xxx
        - --private.api.addr=0.0.0.0:9090
        - --private.api.ratelimit=31872
        - --rpc.returndata.limit=150000
        - --metrics
        - --metrics.addr=0.0.0.0
        - --healthcheck
        - --port=30303
        - --staticpeers=enode://4b808cc15e05401fc192d4aadd90a0516a38da9dd3e75aa9b71b72bbd84c2a27e0056e9275b18507cc146222f2fef6e972e74f65a8228044bcbe53a5e4d1ba0d@[2605:6440:8000:1:199:254:199:239]:30303,enode://f27ae9723ccd90d6a3a1536cc41f91f6680b3dec8641e001302862c9196d44a7eb6e2f3f61f3f4775605cce660c8488589d3137276dd0266b1849a8f520733c1@69.67.149.171:30303,enode://5f66e136aafc4ecec88ea3098869ba0d6a8a8f3af90ed93dafad50fdfda1a1d2c78d123567e594a5e7fc1173ac7b29aa82f3dc2e03f8adacb0335d898d77dc1d@103.219.170.107:30303,enode://96efe55ab3dadd246c9e3ff90641b96c11a10b138e38e9dc79bfb20e9cb4fb0c06918254d5c5bcff6171b0a84293c476e4e4bb2fb1bcf704965a37293b0b0555@82.14.131.227:30304
        - --bootnodes=enode://4b808cc15e05401fc192d4aadd90a0516a38da9dd3e75aa9b71b72bbd84c2a27e0056e9275b18507cc146222f2fef6e972e74f65a8228044bcbe53a5e4d1ba0d@[2605:6440:8000:1:199:254:199:239]:30303,enode://f27ae9723ccd90d6a3a1536cc41f91f6680b3dec8641e001302862c9196d44a7eb6e2f3f61f3f4775605cce660c8488589d3137276dd0266b1849a8f520733c1@69.67.149.171:30303,enode://5f66e136aafc4ecec88ea3098869ba0d6a8a8f3af90ed93dafad50fdfda1a1d2c78d123567e594a5e7fc1173ac7b29aa82f3dc2e03f8adacb0335d898d77dc1d@103.219.170.107:30303,enode://96efe55ab3dadd246c9e3ff90641b96c11a10b138e38e9dc79bfb20e9cb4fb0c06918254d5c5bcff6171b0a84293c476e4e4bb2fb1bcf704965a37293b0b0555@82.14.131.227:30304
        - --db.size.limit=8TB
        - --prune.mode=archive
        - --externalcl
```

Consensus Layer: Nimbus

Consensus Layer Command (with flags/config):
```
exec /home/user/nimbus-eth2/build/nimbus_beacon_node --data-dir=/nimbus-data --enr-auto-update=false --udp-port=9000 --tcp-port=9000 --rest=true --rest-address=0.0.0.0 --rest-port=5052 --metrics=true --metrics-address=0.0.0.0 --metrics-port=8008 --network=holesky --history=archive --el=http://localhost:8551 --jwt-secret="/nimbus-data/jwtsecret" --bootstrap-node=enr:-Mq4QFuhZwXIAtXdj7DpD-KARK9Q1dPwPgfZUXr8GlqbiyEHVu4sVlbGQs7VbUjKq_fz18uhqRz-1anjrZW7SNIIIneGAZVB0eklh2F0dG5ldHOIAAAAAAAAAACEZXRoMpABniGtBwFwAP__________gmlkgnY0gmlwhE-JZV6EcXVpY4IyyIlzZWNwMjU2azGhAq9OfKYbLyFfMIaIw71_P3jiUJGg4IwiOQ2zNq8nu9YXiHN5bmNuZXRzAIN0Y3CCZIyDdWRwgmSM,enr:-Mq4QK_Dpg8RBDNQistboAVLLRIkI45fAGuOQ21XToMQDu5XY6mLWjbjvkl1v3ji8sOh4kxcqQFiWmwiGwA3SlmP-8OGAZVB0ekmh2F0dG5ldHOIAAAMAAAAAACEZXRoMpABniGtBwFwAP__________gmlkgnY0gmlwhE-JZV6EcXVpY4IyyIlzZWNwMjU2azGhAq9OfKYbLyFfMIaIw71_P3jiUJGg4IwiOQ2zNq8nu9YXiHN5bmNuZXRzAIN0Y3CCZIyDdWRwgmSM,enr:-Mq4QBMFznP2Y0OSAnC717HpqxFXOYBGxoxFun6hIGlnxPs3ZPxPG2n_10SuKnm1HylqeP19xwORGYeMt5wlhIbVc2yGAZVB0eknh2F0dG5ldHOIAAAMAAAAAACEZXRoMpABniGtBwFwAP__________gmlkgnY0gmlwhE-JZV6EcXVpY4IyyIlzZWNwMjU2azGhAq9OfKYbLyFfMIaIw71_P3jiUJGg4IwiOQ2zNq8nu9YXiHN5bmNuZXRzB4N0Y3CCZIyDdWRwgmSM,enr:-Mq4QHqsiFx8H0-M-tBvWS2RoRpTReX8dTpP97VAjQAIl0XwZk78Y5CPlnO6GqfTxJpbKreoaTEd6xWSCjbJ2e4JxvqGAZVB89cBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpABniGtBwFwAP__________gmlkgnY0gmlwhKITZ4iEcXVpY4IyyIlzZWNwMjU2azGhAxPkpAHShflJSq9ueoJlvZ11Wf8kx2_jZpxPRf9bmJj1iHN5bmNuZXRzAIN0Y3CCZI2DdWRwgmSN,enr:-Mq4QHt9S30rtVarg9mYnDGTDT8013hgEenRbSnR5FmUVRbvQmqDWXLEqFKh63CxmD6NyyC0gl2RRsJ_HsEjauN2mjyGAZVB89cCh2F0dG5ldHOIAAAAAAAAAGCEZXRoMpABniGtBwFwAP__________gmlkgnY0gmlwhKITZ4iEcXVpY4IyyIlzZWNwMjU2azGhAxPkpAHShflJSq9ueoJlvZ11Wf8kx2_jZpxPRf9bmJj1iHN5bmNuZXRzAIN0Y3CCZI2DdWRwgmSN,enr:-Mq4QMPd9USycvu5i17_27pxQqlfwablXbrFvFmzENwm9mwuHz7OZySPHKTyVWqUpuONN9JkTPA6ZfLlHBIpdg4c_DOGAZVB89cDh2F0dG5ldHOIAAAAAAAAAGCEZXRoMpABniGtBwFwAP__________gmlkgnY0gmlwhKITZ4iEcXVpY4IyyIlzZWNwMjU2azGhAxPkpAHShflJSq9ueoJlvZ11Wf8kx2_jZpxPRf9bmJj1iHN5bmNuZXRzDYN0Y3CCZI2DdWRwgmSN
```

Chain/Network: Holesky

#### Expected behaviour
eth_getTransactionReceipt throwing correct response

#### Actual behaviour
```
curl -X POST --data '{
  "jsonrpc":"2.0",
  "method":"eth_getTransactionReceipt",
  "params":["0x4943e69c4c6a6a01c840ccfb8d4281b19ab8f5971d114902d9d10820570a5fd3"],
  "id":1
}' -H "Content-Type: application/json"  http://localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"getReceipt error: seek with txNum=6850 but data before txNum=118750000 is not available"}}
```

#### Steps to reproduce the behaviour
syncing holesky with erigon3 from scratch, wait until fully sync, test eth_getTransactionReceipt command

#### Backtrace

````
[INFO] [03-18|03:37:28.037] [4/6 Execution] Unwind Execution         from=3510768 to=3510767
[INFO] [03-18|03:37:28.038] aggregator unwind                        step=78 txUnwindTo=122989453 stepsRangeInDB="accounts:0.7, storage:0.7, code:0.7, commitment:0.0, receipt:0.7, logaddrs: 0.7, logtopics: 0.7, tracesfrom: 0.7, tracesto: 0.7"
[WARN] [03-18|03:37:37.653] [rpc] served                             conn=127.0.0.1:43986 method=eth_getTransactionReceipt reqid=1 err="getReceipt error: seek with txNum=6850 but data before txNum=118750000 is not available"


[WARN] [03-18|03:37:51.457] [rpc] served                             conn=127.0.0.1:37866 method=eth_getTransactionReceipt reqid=1 err="getReceipt error: seek with txNum=6850 but data before txNum=118750000 is not available"
[INFO] [03-18|03:38:02.108] [4/6 Execution] Done Commit every block  blk=3510771 blks=5 blk/s=36.5 txs=50 tx/s=365 gas/s=97.61M buf=1.7MB/512.0MB stepsInDB=0.00 step=78.7 inMem=false alloc=7.5GB sys=19.7GB
[INFO] [03-18|03:38:02.240] head updated                             hash=0xeed786d3036b456bc6962e1c5a12c07e4cbf25b37d41826f1a8bee06cde13bd3 number=3510771 age=2s commit=1.185428ms alloc=7.5GB sys=19.7GB
````

**Comment by Giulio2002** [comment]
@michelemodolo trigger a file release, which should fix this

**Comment by darinvhs** [comment]
Hi @Giulio2002, will there be a new release to fix this issue? I’ve tried resyncing my nodes multiple times using --prune.mode=archive, but the problem persists

**Comment by michelemodolo** [comment]
> Hi [@Giulio2002](https://github.com/Giulio2002), will there be a new release to fix this issue? I’ve tried resyncing my nodes multiple times using --prune.mode=archive, but the problem persists

Hi @darinvhs , a new files release is due to be accomplished by about 2 hours so you'll be able to test it (by restarting you node from scratch) before going to bed (I see we're living in pretty different time zones).

**Comment by Giulio2002** [comment]
@darinvhs wait a few minutes please. I will ping you when to resync

**Comment by Giulio2002** [comment]
files were released https://github.com/erigontech/erigon-snapshot/pull/472
