### ISSUE TITLE
Polygon stuck on snapshots download "no metadata yet"

### ISSUE THREAD

**Issue by luono** [erigontech/erigon#15309]
#### System information

Erigon version: 3.0.4

OS & Version: Ubuntu 24.04

Erigon Command (with flags/config):

./erigon --chain=bor-mainnet --datadir=/node/data --torrent.download.rate=1024mb --http.addr="0.0.0.0" --http.port=12588 --http.api=eth,web3,net,debug,trace,txpool --port 30305 --db.size.limit=4T --db.pagesize=16k --batchSize=1024M --sync.loop.block.limit=10000 --prune.mode=archive --bor.heimdall=https://heimdall-api.polygon.technology

#### Actual behaviour

INFO[05-28|20:19:36.087] [1/1 OtterSync] Downloading              progress="(1233/1253 files) 100.00% - 32.0GB/32.0GB" time-left=999hrs:99m total-time=20s download-rate=0B/s completion-rate=0B/s alloc=141.9MB sys=412.4MB
INFO[05-28|20:19:36.091] [snapshots] no metadata yet              files=20 list=v1-071800-071900-bodies.idx,v1-071600-071700-bodies.idx,v1-071800-071900-bodies.seg,v1-072000-072010-headers.seg,v1-071900-072000-headers.idx,...

I have restart erigon many times. It's not working.

**Comment by jajaislanina** [comment]
Dropped everything (provisioned new disk), fresh start of Erigon 3.0.4 with remote heimdall - still same issue.

```
[INFO] [05-29|10:36:20.342] [1/1 OtterSync] Downloading              progress="(1233/1301 files) 100.00% - 32.0GB/32.0GB" time-left=999hrs:99m total-time=12m40s download-rate=0B/s completion-rate=0B/s alloc=199.8MB sys=9.0GB
[INFO] [05-29|10:36:20.349] [snapshots] no metadata yet              files=68 list=v1-071800-071900-bodies.idx,v1-072060-072070-bodies.idx,v1-072091-072092-headers.seg,v1-072090-072091-bodies.idx,v1-072000-072010-bodies.seg,...
```

**Comment by luono** [comment]
> Please clean whole datadir, not only chaindata

I‘ve cleaned the whole datadir many times and restarted erigon.  Still not work.

**Comment by AskAlexSharov** [comment]
hmm... will take a look tomorrow

**Comment by jajaislanina** [comment]
Let me know if you need more logs/testing.
We need to setup archive node pretty urgently so i am mainly focused on this issue atm.

**Comment by elie765** [comment]
same here, stuck on file 1233 with v3.0.4. 
I tried to run with the most recents commits, which run ok, but after downloading the 945GO files, got an issue with blocks missing in snapshots.
Also tried to downgrade until v3.0.1, same issue, stuck on 1233/1301.

**Comment by AskAlexSharov** [comment]
Hi. Please try now (from empty datadir).

**Comment by elie765** [comment]
`[INFO] [05-30|05:47:41.579] [snapshots] no metadata yet              files=44 list=v1-072132-072133-headers.idx,v1-072100-072110-headers.idx,v1-071600-071700-bodies.idx,v1-072120-072130-headers.seg,v1-071700-071800-headers.idx,...
[INFO] [05-30|05:47:41.730] [mem] memory stats                       Rss=39.3GB Size=0B Pss=39.3GB SharedClean=4.0KB SharedDirty=0B PrivateClean=32.0GB PrivateDirty=7.3GB Referenced=39.3GB Anonymous=7.3GB Swap=0B alloc=5.9GB sys=7.3GB
[INFO] [05-30|05:48:01.575] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=0hrs:0m total-time=6m20s download-rate=45.4MB/s completion-rate=45.6MB/s alloc=6.0GB sys=7.3GB
[INFO] [05-30|05:48:01.579] [snapshots] no metadata yet              files=44 list=v1-071800-071900-bodies.seg,v1-072000-072100-bodies.idx,v1-072120-072130-bodies.seg,v1-072130-072131-headers.idx,v1-072131-072132-bodies.seg,...
[INFO] [05-30|05:48:21.575] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=0hrs:0m total-time=6m40s download-rate=22.7MB/s completion-rate=22.8MB/s alloc=5.0GB sys=7.3GB
[INFO] [05-30|05:48:21.579] [snapshots] no metadata yet              files=44 list=v1-072132-072133-headers.idx,v1-072100-072110-headers.idx,v1-071600-071700-bodies.idx,v1-071700-071800-headers.idx,v1-072120-072130-headers.seg,...
[INFO] [05-30|05:48:41.576] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=0hrs:0m total-time=7m0s download-rate=11.4MB/s completion-rate=11.4MB/s alloc=5.0GB sys=7.3GB
[INFO] [05-30|05:48:41.580] [snapshots] no metadata yet              files=44 list=v1-072120-072130-bodies.idx,v1-071700-071800-headers.seg,v1-072110-072120-headers.seg,v1-072120-072130-headers.idx,v1-072132-072133-bodies.seg,...
[INFO] [05-30|05:49:01.575] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=0hrs:0m total-time=7m20s download-rate=5.7MB/s completion-rate=5.7MB/s alloc=5.0GB sys=7.3GB
[INFO] [05-30|05:49:01.579] [snapshots] no metadata yet              files=44 list=v1-072120-072130-bodies.seg,v1-072130-072131-headers.idx,v1-072131-072132-bodies.seg,v1-072130-072131-bodies.idx,v1-072100-072110-bodies.idx,...
[INFO] [05-30|05:49:11.576] [p2p] GoodPeers                          eth68=18 eth67=1
[INFO] [05-30|05:49:21.575] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=0hrs:0m total-time=7m40s download-rate=2.8MB/s completion-rate=2.9MB/s alloc=5.0GB sys=7.3GB
[INFO] [05-30|05:49:21.580] [snapshots] no metadata yet              files=44 list=v1-072131-072132-bodies.idx,v1-072132-072133-headers.seg,v1-072110-072120-bodies.seg,v1-071600-071700-headers.idx,v1-072000-072100-headers.seg,...
[INFO] [05-30|05:49:41.575] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=0hrs:0m total-time=8m0s download-rate=1.4MB/s completion-rate=1.4MB/s alloc=5.0GB sys=7.3GB
[INFO] [05-30|05:49:41.579] [snapshots] no metadata yet              files=44 list=v1-072100-072110-bodies.seg,v1-071900-072000-bodies.idx,v1-071800-071900-bodies.seg,v1-072000-072100-bodies.idx,v1-072120-072130-bodies.seg,...
[INFO] [05-30|05:50:01.576] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=0hrs:0m total-time=8m20s download-rate=726.6KB/s completion-rate=729.8KB/s alloc=5.0GB sys=7.3GB
[INFO] [05-30|05:50:01.580] [snapshots] no metadata yet              files=44 list=v1-071600-071700-headers.idx,v1-072000-072100-headers.seg,v1-071900-072000-headers.seg,v1-072130-072131-headers.seg,v1-071600-071700-headers.seg,...
[INFO] [05-30|05:50:21.575] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=0hrs:0m total-time=8m40s download-rate=363.3KB/s completion-rate=364.9KB/s alloc=138.1MB sys=7.3GB
[INFO] [05-30|05:50:21.579] [snapshots] no metadata yet              files=44 list=v1-071900-072000-bodies.seg,v1-072131-072132-headers.seg,v1-072110-072120-headers.idx,v1-072000-072100-bodies.seg,v1-072110-072120-bodies.idx,...`

no changes for me. I flushed datadir, repulled v3.0.4, still stuck.

**Comment by luono** [comment]
Same result too.

INFO[05-30|09:36:52.911] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=999hrs:99m total-time=52m0s download-rate=0B/s completion-rate=0B/s alloc=365.5MB sys=5.5GB
INFO[05-30|09:36:52.916] [snapshots] no metadata yet              files=44 list=v1-071800-071900-headers.idx,v1-071600-071700-bodies.idx,v1-071600-071700-headers.seg,v1-071700-071800-bodies.idx,v1-072130-072131-headers.idx,...

**Comment by ztjhatjy** [comment]
Same result too, from empty datadir.

**Comment by jajaislanina** [comment]
Also the same here

```
[INFO] [05-30|11:06:48.219] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=999hrs:99m total-time=2h44m0s download-rate=0B/s completion-rate=0B/s alloc=448.2MB sys=9.6GB
[INFO] [05-30|11:06:48.236] [snapshots] no metadata yet              files=44 list=v1-072130-072131-bodies.seg,v1-072000-072100-headers.seg,v1-071600-071700-bodies.seg,v1-071900-072000-headers.idx,v1-072000-072100-bodies.idx,...
```

**Comment by ztjhatjy** [comment]
Please resolve this as soon as possible

INFO[05-30|15:45:28.560] [snapshots] no metadata yet              files=44 list=v1-071600-071700-bodies.seg,v1-071600-071700-headers.idx,v1-072130-072131-headers.seg,v1-071800-071900-headers.idx,v1-072000-072100-headers.seg,...
INFO[05-30|15:45:48.552] [1/1 OtterSync] Downloading              progress="(1233/1277 files) 100.00% - 32.0GB/32.0GB" time-left=999hrs:99m total-time=1m0s download-rate=0B/s completion-rate=0B/s alloc=104.7MB sys=356.6MB

**Comment by AskAlexSharov** [comment]
fixed

**Comment by elie765** [comment]
I still cannot make it work.
and Ethereum mainnet also broken and stop downloading exactly like polygon. I succeed with Ethereum mainnet 2 days ago, but for some reason have to restart the process, and now it stay stuck at "no metadata yet"

For polygon/ottersync this is my outcome: 

> [INFO] [06-01|05:42:54.336] Opening Database                         label=heimdall path=/erigon-data/heimdall
[INFO] [06-01|05:42:54.343] Opening Database                         label=polygon-bridge path=/erigon-data/polygon-bridge
[INFO] [06-01|05:42:54.350] [p2p.message.listener] running p2p message listener component 
[INFO] [06-01|05:42:54.350] [p2p.peerTracker] running peer tracker component 
[INFO] [06-01|05:42:54.394] Started P2P networking                   version=68 self=enode://18f52f4275aca59c2d607edbd5a0c3f2ba4cc10d5d446d208fde8880dd1a86020de22579759e03d571f0a844b743806e7dfe7ad93b21d11d3bb2b44f22fd2f7c@82.64.209.111:30303 name=erigon/v1.3.8-1daeb8bc/linux-amd64/go1.23.9
[INFO] [06-01|05:42:54.649] [snapshots] no metadata yet              files=48 list=v1-069130-069140-headers.seg,v1-069100-069110-headers.idx,v1-069130-069140-bodies.seg,v1-069142-069143-bodies.idx,v1-069147-069148-headers.seg,...
[INFO] [06-01|05:42:54.650] [snapshots] no progress yet              files=863 list=v1-053700-053800-headers.seg,v1-057600-057700-headers.seg,v1-064600-064700-headers.seg,v1-059100-059200-bodies.seg,v1-066640-066641-bodies.idx,...
unexpected fault address 0x7e59b8400020
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7e59b8400020 pc=0x49d3ee]

goroutine 45861 gp=0xc00f55d500 m=11 mp=0xc004522008 [running]:
runtime.throw({0x2fcb78a?, 0x30?})
        runtime/panic.go:1073 +0x48 fp=0xc00ea6f2c0 sp=0xc00ea6f290 pc=0x4939c8
runtime.sigpanic()
        runtime/signal_unix.go:914 +0x10a fp=0xc00ea6f320 sp=0xc00ea6f2c0 pc=0x495aea
runtime.memmove()
        runtime/memmove_amd64.s:372 +0x42e fp=0xc00ea6f328 sp=0xc00ea6f320 pc=0x49d3ee
github.com/anacrolix/torrent/mmap_span.copyBytes(...)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/mmap_span/mmap_span.go:148

**Comment by WangXiaopai595** [comment]
I also encountered this problem in version v3.0.3

```

[INFO] [06-01|14:10:58.378] [1/1 OtterSync] Downloading              progress="(7817/7817 files) 92.03% - 4.8TB/5.3TB" time-left=999hrs:99m total-time=17m20s download-rate=0B/s completion-rate=0B/s alloc=2.5GB sys=4.5GB
[INFO] [06-01|14:10:58.526] [snapshots] no progress yet              files=8 list=domain/v1-commitment.3072-3328.kv,domain/v1-commitment.2048-3072.kv,domain/v1-commitment.3328-3392.kv,domain/v1-commitment.3072-3328.kvi,domain/v1-commitment.2048-3072.kvi,...
[INFO] [06-01|14:11:18.378] [1/1 OtterSync] Downloading              progress="(7817/7817 files) 92.03% - 4.8TB/5.3TB" time-left=999hrs:99m total-time=17m40s download-rate=0B/s completion-rate=0B/s alloc=2.6GB sys=4.5GB
[INFO] [06-01|14:11:18.535] [snapshots] no progress yet              files=8 list=domain/v1-commitment.3072-3328.kv,domain/v1-commitment.2048-3072.kv,domain/v1-commitment.3328-3392.kv,domain/v1-commitment.3072-3328.kvi,domain/v1-commitment.2048-3072.kvi,...
[INFO] [06-01|14:11:38.377] [1/1 OtterSync] Downloading              progress="(7817/7817 files) 92.03% - 4.8TB/5.3TB" time-left=999hrs:99m total-time=18m0s download-rate=0B/s completion-rate=0B/s alloc=2.6GB sys=4.5GB
[INFO] [06-01|14:11:38.377] [p2p] GoodPeers                          eth68=42 eth67=1
[INFO] [06-01|14:11:38.528] [snapshots] no progress yet              files=8 list=domain/v1-commitment.3072-3328.kv,domain/v1-commitment.2048-3072.kv,domain/v1-commitment.3328-3392.kv,domain/v1-commitment.3072-3328.kvi,domain/v1-commitment.2048-3072.kvi,...

```

**Comment by AskAlexSharov** [comment]
@WangXiaopai595 restart erigon

**Comment by WangXiaopai595** [comment]
> [@WangXiaopai595](https://github.com/WangXiaopai595)重启埃里贡

I restarted many times to no avail
```

[INFO] [06-01|15:53:54.369] Starting Erigon on Bor Mainnet... 
[INFO] [06-01|15:53:54.371] Maximum peer count                       total=1000
[INFO] [06-01|15:53:54.371] starting HTTP APIs                       port=8545 APIs=eth,erigon,engine
[INFO] [06-01|15:53:54.374] Set global gas cap                       cap=50000000
[INFO] [06-01|15:53:54.376] torrent verbosity                        level=WRN
[INFO] [06-01|15:53:56.631] [Downloader] Running with                ipv6-enabled=true ipv4-enabled=true download.rate=128mb upload.rate=4mb
[INFO] [06-01|15:53:56.632] Opening Database                         label=chaindata path=/data/chaindata
meta_validate:26677 meta[0] has invalid txnid 0, skip it
meta_validate:26677 meta[2] has invalid txnid 0, skip it
meta_validate:26677 meta[0] has invalid txnid 0, skip it
meta_validate:26677 meta[2] has invalid txnid 0, skip it
[INFO] [06-01|15:53:56.636] [db] open                                label=chaindata sizeLimit=8TB pageSize=16KB
[WARN] [06-01|15:53:56.647] Sanitizing invalid bor miner gas price   provided=1000000000 updated=25000000000
[WARN] [06-01|15:53:56.647] Sanitizing invalid bor min fee cap       provided=1 updated=25000000000.000
[INFO] [06-01|15:53:56.647] Initialised chain configuration          config="{ChainID: 137, Agra: 50523000, Napoli: 54876000, Ahmedabad: 62278656, Engine: bor}" genesis=0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
[DBUG] [06-01|15:53:56.647] [rpc] download of segments not complete yet. please wait StageSnapshots to finish 
[DBUG] [06-01|15:53:56.653] [db] open                                label=downloader sizeLimit=16GB pageSize=4KB
[INFO] [06-01|15:54:37.993] [snapshots] Adding .torrent files        progress=7023/7817
[DBUG] [06-01|15:54:43.904] [snapshots.webseed] providers            http=1 disk=0
[INFO] [06-01|15:54:43.905] Initialising Ethereum protocol           network=137
[INFO] [06-01|15:54:43.905] Opening Database                         label=bor path=/data/bor
meta_validate:26677 meta[0] has invalid txnid 0, skip it
meta_validate:26677 meta[2] has invalid txnid 0, skip it
meta_validate:26677 meta[0] has invalid txnid 0, skip it
meta_validate:26677 meta[2] has invalid txnid 0, skip it
[DBUG] [06-01|15:54:43.912] [db] open                                label=consensus sizeLimit=2TB pageSize=16KB
[INFO] [06-01|15:54:43.917] new subscription to logs established 
[INFO] [06-01|15:54:43.917] rpc filters: subscribing to Erigon events 
[INFO] [06-01|15:54:43.917] Starting private RPC server              on=0.0.0.0:9090
[DBUG] [06-01|15:54:43.917] Establishing event subscription channel with the RPC daemon ... 
[INFO] [06-01|15:54:43.917] new subscription to newHeaders established 
[INFO] [06-01|15:54:43.919] starting rpc with polygon bridge 
[DBUG] [06-01|15:54:43.919] [agg] merge                              collate_workers=1 merge_workers=1 compress_workers=1
[INFO] [06-01|15:54:43.921] [rpc] endpoint opened                    ws=false ws.compression=true grpc=false http.url=127.0.0.1:8545
[DBUG] [06-01|15:54:43.924] [db] open                                label=sentry sizeLimit=8GB pageSize=4KB
[DBUG] [06-01|15:54:43.929] [db] open                                label=sentry sizeLimit=8GB pageSize=4KB
[INFO] [06-01|15:54:43.930] [sync] running sync service component 
[INFO] [06-01|15:54:43.930] [sync] waiting for execution client 
[INFO] [06-01|15:54:43.930] [sync] running tip events component 
[INFO] [06-01|15:54:43.930] [bor.heimdall] running heimdall service component 
[INFO] [06-01|15:54:43.930] Opening Database                         label=polygon-bridge path=/data/polygon-bridge
[INFO] [06-01|15:54:43.930] Opening Database                         label=heimdall path=/data/heimdall
[INFO] [06-01|15:54:43.930] [p2p] running p2p service component 
[INFO] [06-01|15:54:43.930] [p2p-publisher] running publisher component 
[INFO] [06-01|15:54:43.930] [p2p.message.listener] running p2p message listener component 
[INFO] [06-01|15:54:43.930] [sync] running execution client store component 
[INFO] [06-01|15:54:43.930] [p2p.peerTracker] running peer tracker component 
[WARN] [06-01|15:54:43.936] NAT ExternalIP resolution has failed, try to pass a different --nat option err="no UPnP or NAT-PMP router discovered"
meta_validate:26677 meta[0] has invalid txnid 0, skip it
meta_validate:26677 meta[2] has invalid txnid 0, skip it
meta_validate:26677 meta[0] has invalid txnid 0, skip it
meta_validate:26677 meta[2] has invalid txnid 0, skip it
[DBUG] [06-01|15:54:43.937] [db] open                                label=heimdall sizeLimit=16GB pageSize=4KB
meta_validate:26677 meta[0] has invalid txnid 0, skip it
meta_validate:26677 meta[2] has invalid txnid 0, skip it
meta_validate:26677 meta[0] has invalid txnid 0, skip it
meta_validate:26677 meta[2] has invalid txnid 0, skip it
[DBUG] [06-01|15:54:43.941] [db] open                                label=polygon-bridge sizeLimit=16GB pageSize=4KB
[WARN] [06-01|15:54:43.941] NAT ExternalIP resolution has failed, try to pass a different --nat option err="no UPnP or NAT-PMP router discovered"
[DBUG] [06-01|15:54:43.947] Couldn't add port mapping                proto=tcp extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
[DBUG] [06-01|15:54:43.947] Couldn't add port mapping                proto=udp extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
[DBUG] [06-01|15:54:43.952] Couldn't add port mapping                proto=tcp extport=30304 intport=30304 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
[DBUG] [06-01|15:54:43.952] Couldn't add port mapping                proto=udp extport=30304 intport=30304 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
[INFO] [06-01|15:54:43.958] [OtterSync] Starting Ottersync 
[INFO] [06-01|15:54:43.958] 
   _____ _             _   _                ____  _   _                                       
  / ____| |           | | (_)              / __ \| | | |                                      
 | (___ | |_ __ _ _ __| |_ _ _ __   __ _  | |  | | |_| |_ ___ _ __ ___ _   _ _ __   ___       
  \___ \| __/ _ | '__| __| | '_ \ / _ | | |  | | __| __/ _ \ '__/ __| | | | '_ \ / __|      
  ____) | || (_| | |  | |_| | | | | (_| | | |__| | |_| ||  __/ |  \__ \ |_| | | | | (__ _ _ _ 
 |_____/ \__\__,_|_|   \__|_|_| |_|\__, |  \____/ \__|\__\___|_|  |___/\__, |_| |_|\___(_|_|_)
                                    __/ |                               __/ |                 
                                   |___/                               |___/                                            


                                        .:-===++**++===-:                                 
                                   :=##%@@@@@@@@@@@@@@@@@@%#*=.                           
                               .=#@@@@@@%##+====--====+##@@@@@@@#=.     ...               
                   .=**###*=:+#@@@@%*=:.                  .:=#%@@@@#==#@@@@@%#-           
                 -#@@@@%%@@@@@@%+-.                            .=*%@@@@#*+*#@@@%=         
                =@@@*:    -%%+:                                    -#@+.     =@@@-        
                %@@#     +@#.                                        :%%-     %@@*        
                @@@+    +%=.     -+=                        :=-       .#@-    %@@#        
                *@@%:  #@-      =@@@*                      +@@@%.       =@= -*@@@:        
                 #@@@##@+       #@@@@.                     %@@@@=        #@%@@@#-         
                  :#@@@@:       +@@@#       :=++++==-.     *@@@@:        =@@@@-           
                  =%@@%=         +#*.    =#%#+==-==+#%%=:  .+#*:         .#@@@#.          
                 +@@%+.               .+%+-.          :=##-                :#@@@-         
                -@@@=                -%#:     ..::.      +@*                 +@@%.        
    .::-========*@@@..              -@#      +%@@@@%.     -@#               .-@@@+=======-
.:-====----:::::#@@%:--=::::..      #@:      *@@@@@%:      *@=      ..:-:-=--:@@@+::::----
                =@@@:.......        @@        :+@#=.       -@+        .......-@@@:        
       .:=++####*%@@%=--::::..      @@   %#     %*    :@*  -@+      ...::---+@@@#*#*##+=-:
  ..--==::..     :%@@@-   ..:::..   @@   +@*:.-#@@+-.-#@-  -@+   ..:::..  .+@@@#.     ..:-
                  .#@@@##-:.        @@    :+#@%=.:+@@#=.   -@+        .-=#@@@@+           
             -=+++=--+%@@%+=.       @@       +%*=+#%-      -@+       :=#@@@%+--++++=:     
         .=**=:.      .=*@@@@@#=:.  @@         :--.        -@+  .-+#@@@@%+:       .:=*+-. 
        ::.              .=*@@@@@@%#@@+=-:..         ..::=+#@%#@@@@@@%+-.             ..-.
                            ..=*#@@@@@@@@@@@@@@@%%@@@@@@@@@@@@@@%#+-.                     
                                  .:-==++*#######%######**+==-:                           

             
 
[INFO] [06-01|15:54:43.958] [1/1 OtterSync] Requesting downloads 
[DBUG] [06-01|15:54:43.959] QuerySeeds read nodes from the node DB   count=0
[INFO] [06-01|15:54:43.959] Started P2P networking                   version=68 self=enode://e9103c6c6d2a5cab91e6e485888607650d36ffa3654cc911b9dc38abecf7dca11c25747ed9e7981245deda206a71fd5f39d9885474ffe571149da29becdcbc90@127.0.0.1:30303 name=erigon/v3.0.4-406d855f/linux-amd64/go1.23.9
[DBUG] [06-01|15:54:43.960] QuerySeeds read nodes from the node DB   count=0
[DBUG] [06-01|15:54:43.964] QuerySeeds read nodes from the node DB   count=0
[INFO] [06-01|15:54:43.964] Started P2P networking                   version=67 self=enode://e9103c6c6d2a5cab91e6e485888607650d36ffa3654cc911b9dc38abecf7dca11c25747ed9e7981245deda206a71fd5f39d9885474ffe571149da29becdcbc90@127.0.0.1:30304 name=erigon/v3.0.4-406d855f/linux-amd64/go1.23.9
[DBUG] [06-01|15:54:43.964] [p2p.peerTracker] replayed current state of connected peers count=0
[DBUG] [06-01|15:54:43.964] QuerySeeds read nodes from the node DB   count=0
[DBUG] [06-01|15:54:44.322] [snapshots] Downloading from torrent     file=domain/v1-commitment.3328-3392.kv peers=0
[DBUG] [06-01|15:54:44.322] [snapshots] Downloading from torrent     file=domain/v1-commitment.2048-3072.kvi peers=0
[DBUG] [06-01|15:54:44.322] [snapshots] Downloading from torrent     file=domain/v1-commitment.3392-3408.kv peers=0
[DBUG] [06-01|15:54:44.322] [snapshots] Downloading from torrent     file=domain/v1-commitment.3392-3408.kvi peers=0
[DBUG] [06-01|15:54:44.322] [snapshots] Downloading from torrent     file=domain/v1-commitment.2048-3072.kv peers=0
[DBUG] [06-01|15:54:44.322] [snapshots] Downloading from torrent     file=domain/v1-commitment.3328-3392.kvi peers=0
[DBUG] [06-01|15:54:44.322] [snapshots] Downloading from torrent     file=domain/v1-commitment.3072-3328.kvi peers=0
[DBUG] [06-01|15:54:44.322] [snapshots] Downloading from torrent     file=domain/v1-commitment.3072-3328.kv peers=0
[INFO] [06-01|15:54:45.298] [snapshots] no progress yet              files=8 list=domain/v1-commitment.3328-3392.kvi,domain/v1-commitment.3072-3328.kvi,domain/v1-commitment.3072-3328.kv,domain/v1-commitment.3328-3392.kv,domain/v1-commitment.2048-3072.kvi,...
[DBUG] [06-01|15:54:45.298] [snapshots] files progress               files=8 list="domain/v1-commitment.2048-3072.kv (0%), domain/v1-commitment.2048-3072.kvi (0%), domain/v1-commitment.3072-3328.kv (0%), domain/v1-commitment.3072-3328.kvi (0%), domain/v1-commitment.3328-3392.kv (0%), domain/v1-commitment.3328-3392.kvi (0%), domain/v1-commitment.3392-3408.kv (0%), domain/v1-commitment.3392-3408.kvi (0%)"
[DBUG] [06-01|15:54:45.298] [snapshots] downloading                  len=7817 torrent=7817 db=8 t-complete=7809 hashed=0B hash-rate=0B/s completed=4.8TB completion-rate=0B/s flushed=0B flush-rate=0B/s downloaded=4.8TB download-rate=0B/s webseed-trips=0 webseed-active=0 webseed-max-active=0 webseed-discards=0 webseed-fails=0 webseed-bytes=0B localHashes=0 localHashTime=0s
[DBUG] [06-01|15:54:46.547] [snapshots.webseed] get from HTTP provider manifest-len=21912 url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network
[DBUG] [06-01|15:54:47.625] [snapshots] got from webseed             name=v1-071200-071300-transactions.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071200-071300-transactions.seg.torrent, .torrent file is not whitelisted 3840fcbb98f5a27eee5f087595af0fca500c3beb" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071200-071300-transactions.seg.torrent
[DBUG] [06-01|15:54:47.645] [snapshots] got from webseed             name=v1-071200-071300-bodies.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071200-071300-bodies.seg.torrent, .torrent file is not whitelisted f7a49a350f70a92b8d62940d76bc532975d13857" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071200-071300-bodies.seg.torrent
[DBUG] [06-01|15:54:47.729] [snapshots] got from webseed             name=v1-071200-071300-borevents.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071200-071300-borevents.idx.torrent, .torrent file is not whitelisted 641c19ca5b7ac157552e4c43293f3a7b5d8a6b77" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071200-071300-borevents.idx.torrent
[DBUG] [06-01|15:54:48.075] [snapshots] got from webseed             name=v1-071400-071500-headers.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071400-071500-headers.idx.torrent, .torrent file is not whitelisted b08faa017ec722444c5fde3f70c39a8d4e5ab33e" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071400-071500-headers.idx.torrent
[DBUG] [06-01|15:54:48.161] [snapshots] got from webseed             name=domain/v1-commitment.3072-3328.kvi.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/domain/v1-commitment.3072-3328.kvi.torrent, .torrent file is not whitelisted 1bd470dddc7224323dda9d991b5a0cae33a2a91f" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.3072-3328.kvi.torrent
[DBUG] [06-01|15:54:48.258] [snapshots] got from webseed             name=domain/v1-commitment.2048-3072.kvi.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/domain/v1-commitment.2048-3072.kvi.torrent, .torrent file is not whitelisted 9c6757fd1242db5b0a0adcd9cc16e5e6dfd8e7c0" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.2048-3072.kvi.torrent
[DBUG] [06-01|15:54:48.284] [snapshots] got from webseed             name=v1-071100-071200-transactions.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071100-071200-transactions.seg.torrent, .torrent file is not whitelisted f1081ea24e1b88f1e0c4ade18f1b537a719bdd29" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071100-071200-transactions.seg.torrent
[DBUG] [06-01|15:54:48.422] [snapshots] got from webseed             name=domain/v1-commitment.3328-3392.kv.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/domain/v1-commitment.3328-3392.kv.torrent, .torrent file is not whitelisted 1d666f213b20aeb9ab697f980f28294d6f30e12a" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.3328-3392.kv.torrent
[DBUG] [06-01|15:54:48.735] [snapshots] got from webseed             name=v1-071100-071200-transactions.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071100-071200-transactions.idx.torrent, .torrent file is not whitelisted a9c0426df27744fd5c316401ccf8e635a73f1f7b" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071100-071200-transactions.idx.torrent
[DBUG] [06-01|15:54:48.815] [snapshots] got from webseed             name=v1-071100-071200-bodies.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071100-071200-bodies.seg.torrent, .torrent file is not whitelisted a079e1cc14009e04d7f586d830f9b4ade994a67c" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071100-071200-bodies.seg.torrent
[DBUG] [06-01|15:54:49.058] [snapshots] got from webseed             name=v1-071100-071200-transactions-to-block.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071100-071200-transactions-to-block.idx.torrent, .torrent file is not whitelisted 360657326ba38450b989f2e1d1e64ea02f2ee041" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071100-071200-transactions-to-block.idx.torrent
[DBUG] [06-01|15:54:49.122] [snapshots] got from webseed             name=v1-071200-071300-transactions.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071200-071300-transactions.idx.torrent, .torrent file is not whitelisted 003c9ffb3fbfab1cf8d8a136be811acb3077f804" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071200-071300-transactions.idx.torrent
[DBUG] [06-01|15:54:49.213] [snapshots] got from webseed             name=v1-071200-071300-headers.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071200-071300-headers.idx.torrent, .torrent file is not whitelisted a47503454468a4ba76888af5bb2b8004269b9208" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071200-071300-headers.idx.torrent
[DBUG] [06-01|15:54:49.280] [snapshots] got from webseed             name=v1-071300-071400-bodies.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071300-071400-bodies.seg.torrent, .torrent file is not whitelisted 0c72295bfd4c33b57a223d42e1942c6fa561f6a6" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071300-071400-bodies.seg.torrent
[DBUG] [06-01|15:54:49.284] [snapshots] got from webseed             name=v1-071300-071400-transactions-to-block.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071300-071400-transactions-to-block.idx.torrent, .torrent file is not whitelisted 42db1e9d26bb97a560e074cf15da7b857deaee52" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071300-071400-transactions-to-block.idx.torrent
[DBUG] [06-01|15:54:49.297] [snapshots] got from webseed             name=v1-071400-071500-bodies.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071400-071500-bodies.idx.torrent, .torrent file is not whitelisted 41ce2f516a4d282c19678bbf5085124c6ba5d835" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071400-071500-bodies.idx.torrent
[DBUG] [06-01|15:54:49.397] [snapshots] got from webseed             name=v1-071100-071200-headers.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071100-071200-headers.seg.torrent, .torrent file is not whitelisted fb3d778f6231a2e84e0188d4a5dc5c44fa11ec3b" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071100-071200-headers.seg.torrent
[DBUG] [06-01|15:54:49.910] [snapshots] got from webseed             name=domain/v1-commitment.3392-3408.kv.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/domain/v1-commitment.3392-3408.kv.torrent, .torrent file is not whitelisted 056ed342df04c8eb23f5cb4afcb47187737000a0" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.3392-3408.kv.torrent
[DBUG] [06-01|15:54:50.323] [snapshots] got from webseed             name=v1-071400-071500-transactions-to-block.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071400-071500-transactions-to-block.idx.torrent, .torrent file is not whitelisted 759a81ffe002dade47679dc1bfad894d4687590a" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071400-071500-transactions-to-block.idx.torrent
[DBUG] [06-01|15:54:50.431] [snapshots] got from webseed             name=v1-071200-071300-bodies.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071200-071300-bodies.idx.torrent, .torrent file is not whitelisted 270c84d61cb4847804b76b0bbf9834d746e01bd6" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071200-071300-bodies.idx.torrent
[DBUG] [06-01|15:54:50.499] [snapshots] got from webseed             name=v1-071300-071400-borevents.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071300-071400-borevents.idx.torrent, .torrent file is not whitelisted 0cac021078a850d3fb0574e10bf970756cd250d6" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071300-071400-borevents.idx.torrent
[DBUG] [06-01|15:54:50.649] [snapshots] got from webseed             name=v1-071400-071500-borevents.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071400-071500-borevents.idx.torrent, .torrent file is not whitelisted fbc1c661d36d1c2f11f7b4e82be33d59a73d93eb" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071400-071500-borevents.idx.torrent
[DBUG] [06-01|15:54:50.767] [snapshots] got from webseed             name=v1-071300-071400-headers.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071300-071400-headers.seg.torrent, .torrent file is not whitelisted 8ce36dd03f85e218e2d6427b673fe6f6131ca361" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071300-071400-headers.seg.torrent
[DBUG] [06-01|15:54:50.778] [snapshots] got from webseed             name=v1-071100-071200-borevents.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071100-071200-borevents.idx.torrent, .torrent file is not whitelisted 8f48ed00a630caba0be3ed9e5c6da8b1bf1ac48f" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071100-071200-borevents.idx.torrent
[DBUG] [06-01|15:54:50.885] [snapshots] got from webseed             name=domain/v1-commitment.2048-3072.kv.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/domain/v1-commitment.2048-3072.kv.torrent, .torrent file is not whitelisted 42de9c8460ca5ce0d8f005b4c19f562766b65cc2" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.2048-3072.kv.torrent
[DBUG] [06-01|15:54:51.155] [snapshots] got from webseed             name=v1-071100-071200-headers.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071100-071200-headers.idx.torrent, .torrent file is not whitelisted 1f32dddd72634f5c4a816cb9490aa3395296a0b1" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071100-071200-headers.idx.torrent
[DBUG] [06-01|15:54:51.170] [snapshots] got from webseed             name=v1-071000-071100-transactions-to-block.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071000-071100-transactions-to-block.idx.torrent, .torrent file is not whitelisted eb1f4c6e1ce97e10e8c101d522e51a0393f2c5c3" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071000-071100-transactions-to-block.idx.torrent
[DBUG] [06-01|15:54:51.383] [snapshots] got from webseed             name=v1-071200-071300-headers.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071200-071300-headers.seg.torrent, .torrent file is not whitelisted 5dcea6f798f9a5181d1a5aad19368c792990dfbc" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071200-071300-headers.seg.torrent
[DBUG] [06-01|15:54:51.696] [snapshots] got from webseed             name=domain/v1-commitment.3392-3408.kvi.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/domain/v1-commitment.3392-3408.kvi.torrent, .torrent file is not whitelisted b1cf07d7abd484e1b660a7c1af9cd4f742fc17a0" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.3392-3408.kvi.torrent
[DBUG] [06-01|15:54:51.732] [snapshots] got from webseed             name=v1-071000-071100-borevents.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071000-071100-borevents.idx.torrent, .torrent file is not whitelisted 4d7cf921cb4b601eef7b5f8843a6f5a323f6daed" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071000-071100-borevents.idx.torrent
[DBUG] [06-01|15:54:51.761] [snapshots] got from webseed             name=v1-071000-071100-transactions.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071000-071100-transactions.idx.torrent, .torrent file is not whitelisted 8f5d8a0f7ee11b38ea0b0a8d4ad804869b6e32ca" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071000-071100-transactions.idx.torrent
[DBUG] [06-01|15:54:52.305] [snapshots] got from webseed             name=v1-071100-071200-bodies.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071100-071200-bodies.idx.torrent, .torrent file is not whitelisted af7a6c80103819e058ecd2f47b916de3b698197f" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071100-071200-bodies.idx.torrent
[DBUG] [06-01|15:54:52.640] [snapshots] got from webseed             name=domain/v1-commitment.3328-3392.kvi.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/domain/v1-commitment.3328-3392.kvi.torrent, .torrent file is not whitelisted 1cd64d4e86b9fa551c8e33d7e91fad8352904f44" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.3328-3392.kvi.torrent
[DBUG] [06-01|15:54:52.857] [snapshots] got from webseed             name=v1-071300-071400-headers.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071300-071400-headers.idx.torrent, .torrent file is not whitelisted 660e539c209e7b90715cbb96b9d54545e42ddd2e" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071300-071400-headers.idx.torrent
[DBUG] [06-01|15:54:52.993] [snapshots] got from webseed             name=v1-071400-071500-transactions.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071400-071500-transactions.seg.torrent, .torrent file is not whitelisted 5c054656f8b3e1a4b27e67f8b0caa71399fcee2c" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071400-071500-transactions.seg.torrent
[DBUG] [06-01|15:54:53.319] [p2p.peerTracker] peer connected         peerId=9344ffa7219ea1b7c02036a484edb1853200d8746536819a87253d41d45fa1e746e899c7f7c8d30c666b36002f1a53fa710c6e69d577c6b1e5eede3dd07fca2f
[DBUG] [06-01|15:54:53.388] [snapshots] got from webseed             name=v1-071400-071500-headers.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071400-071500-headers.seg.torrent, .torrent file is not whitelisted 4f3f7374d92479bc3b2b6e59f78c8115fc3662e2" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071400-071500-headers.seg.torrent
[DBUG] [06-01|15:54:53.449] [snapshots] got from webseed             name=v1-071200-071300-transactions-to-block.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071200-071300-transactions-to-block.idx.torrent, .torrent file is not whitelisted 9a6f1bab3ee6b87b12ff4307164609154921e8b4" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071200-071300-transactions-to-block.idx.torrent
[DBUG] [06-01|15:54:53.534] [snapshots] got from webseed             name=v1-071400-071500-bodies.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071400-071500-bodies.seg.torrent, .torrent file is not whitelisted 8e99d28776e01ad6b0bea4b03f7be4edc6befdae" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071400-071500-bodies.seg.torrent
[DBUG] [06-01|15:54:53.629] [snapshots] got from webseed             name=v1-071300-071400-bodies.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071300-071400-bodies.idx.torrent, .torrent file is not whitelisted 4b7cb5f8e9f9cf7a0e8c1b61f1a538ebf2ce2296" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071300-071400-bodies.idx.torrent
[DBUG] [06-01|15:54:53.630] [snapshots] got from webseed             name=v1-071300-071400-transactions.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071300-071400-transactions.idx.torrent, .torrent file is not whitelisted 52ac7d2c79ef7921393bfdc04d5e3a3e0602e11c" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071300-071400-transactions.idx.torrent
[DBUG] [06-01|15:54:54.086] [snapshots] got from webseed             name=v1-071300-071400-transactions.seg.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071300-071400-transactions.seg.torrent, .torrent file is not whitelisted 8bdac3d97e8e2b06b8f91f0ba14f2af737e8f091" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071300-071400-transactions.seg.torrent
[DBUG] [06-01|15:54:54.231] [snapshots] got from webseed             name=v1-071400-071500-transactions.idx.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/v1-071400-071500-transactions.idx.torrent, .torrent file is not whitelisted 63ecc8fd2b4976ecd3c68b41426e6857a85f5edb" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/v1-071400-071500-transactions.idx.torrent
[DBUG] [06-01|15:54:54.551] [snapshots] got from webseed             name=domain/v1-commitment.3072-3328.kv.torrent err="webseed.downloadTorrentFile: host=erigon3-v1-snapshots-bor-mainnet.erigon.network, url=/domain/v1-commitment.3072-3328.kv.torrent, .torrent file is not whitelisted efb126109c26a89fcc66a28e540bc1ed886e8b4e" url=https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.3072-3328.kv.torrent
[INFO] [06-01|15:55:03.908] [1/1 OtterSync] Downloading              progress="(7817/7817 files) 92.03% - 4.8TB/5.3TB" time-left=999hrs:99m total-time=20s download-rate=0B/s completion-rate=0B/s alloc=4.2GB sys=4.6GB
[INFO] [06-01|15:55:04.051] [snapshots] no progress yet              files=8 list=domain/v1-commitment.3328-3392.kv,domain/v1-commitment.2048-3072.kvi,domain/v1-commitment.3392-3408.kv,domain/v1-commitment.3392-3408.kvi,domain/v1-commitment.2048-3072.kv,...
[DBUG] [06-01|15:55:04.052] [snapshots] files progress               files=8 list="domain/v1-commitment.2048-3072.kv (0%), domain/v1-commitment.2048-3072.kvi (0%), domain/v1-commitment.3072-3328.kv (0%), domain/v1-commitment.3072-3328.kvi (0%), domain/v1-commitment.3328-3392.kv (0%), domain/v1-commitment.3328-3392.kvi (0%), domain/v1-commitment.3392-3408.kv (0%), domain/v1-commitment.3392-3408.kvi (0%)"
[DBUG] [06-01|15:55:04.052] [snapshots] downloading                  len=7817 torrent=7817 db=8 t-complete=7809 hashed=0B hash-rate=0B/s completed=4.8TB completion-rate=0B/s flushed=0B flush-rate=0B/s downloaded=4.8TB download-rate=0B/s webseed-trips=0 webseed-active=0 webseed-max-active=0 webseed-discards=0 webseed-fails=0 webseed-bytes=0B localHashes=0 localHashTime=0s
[DBUG] [06-01|15:55:09.511] [p2p.peerTracker] peer connected         peerId=b069bb283678cc6ef2b36df403176079b4d2468104f1aba1e6b11e309dadbd053285b388b88c37642c74815d6ef142ac8cecdd9696f748bb288f07e1ef1b264b
[DBUG] [06-01|15:55:14.666] [p2p.peerTracker] peer connected         peerId=3cdad392e44b1c2666244c5120eed6f5cddf530d92235e1e525440834ccb00aed783eafc5c2a02812ce29349eea2aaddeb627a51dbce7a0a1145fc7c96d02a84
[INFO] [06-01|15:55:23.906] [1/1 OtterSync] Downloading              progress="(7817/7817 files) 92.03% - 4.8TB/5.3TB" time-left=999hrs:99m total-time=40s download-rate=0B/s completion-rate=0B/s alloc=4.2GB sys=4.6GB
[INFO] [06-01|15:55:24.046] [snapshots] no progress yet              files=8 list=domain/v1-commitment.3328-3392.kv,domain/v1-commitment.2048-3072.kvi,domain/v1-commitment.3392-3408.kv,domain/v1-commitment.3392-3408.kvi,domain/v1-commitment.2048-3072.kv,...
[DBUG] [06-01|15:55:24.046] [snapshots] files progress               files=8 list="domain/v1-commitment.2048-3072.kv (0%), domain/v1-commitment.2048-3072.kvi (0%), domain/v1-commitment.3072-3328.kv (0%), domain/v1-commitment.3072-3328.kvi (0%), domain/v1-commitment.3328-3392.kv (0%), domain/v1-commitment.3328-3392.kvi (0%), domain/v1-commitment.3392-3408.kv (0%), domain/v1-commitment.3392-3408.kvi (0%)"
[DBUG] [06-01|15:55:24.046] [snapshots] downloading                  len=7817 torrent=7817 db=8 t-complete=7809 hashed=0B hash-rate=0B/s completed=4.8TB completion-rate=0B/s flushed=0B flush-rate=0B/s downloaded=4.8TB download-rate=0B/s webseed-trips=0 webseed-active=0 webseed-max-active=0 webseed-discards=0 webseed-fails=0 webseed-bytes=0B localHashes=0 localHashTime=0s

```

**Comment by WangXiaopai595** [comment]
> [@WangXiaopai595](https://github.com/WangXiaopai595) restart erigon

I have found the problem. Some resources have 403 errors in http, such as: https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.2048-3072.kv, but https://erigon3-v1-snapshots-bor-mainnet.erigon.network/domain/v1-commitment.2048-3072.kv.torrent can be downloaded normally.

**Comment by jajaislanina** [comment]
It's working for me now. Downloaded 5TB snapshot and started syncing. Thanks @AskAlexSharov

**Comment by AskAlexSharov** [comment]
Fuf
