### ISSUE TITLE
historical `eth_getProof` fails on some requests on hoodi

### ISSUE THREAD

**Issue by Giulio2002** [erigontech/erigon#15924]
login into hoodi snapshotter (or any node) and try:

`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getProof","params":["0xa2d37135730df5ada5da7fcaecfbf540271ed3c9",[],"0x7a1b0"],"id":1}' http://localhost:8545`

`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getProof","params":["0xa2d37135730df5ada5da7fcaecfbf540271ed3c9",[],"0x7a1ae"],"id":1}' http://localhost:8545`

`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getProof","params":["0x029d946f28f93399a5b0d09c879fc8c94e596aeb",[],"0x7a1a2"],"id":1}' http://localhost:8545`

**Comment by VBulikov** [comment]
VBulikov added Imp2 as Importance

**Comment by awskii** [comment]
Got proofs for first two queries, third one is different

**Comment by awskii** [comment]
cell (6, 3, depth=7) {loaded=false addr=e3b4f841 balance=0 nonce=0 codeHash=EMPTY memHash=6aac2e4b198f887171f382a8e7de3773a02234a3f9a2841f83cf4f528dd2c81a }
cell (6, 8, depth=7) {loaded=false h=e45079ab41ccd1dbf5fdda418726d22d2a34e5e719a5324df3037c097eaff5e3 }
cell (6, c, depth=7) {loaded=false addr=baccfb48 balance=0 nonce=0 codeHash=EMPTY memHash=cd41ae269e5381d3df1490b28e405527300d5456e15bd855b868d7b13c41ecbc }

address seems to be non-replaced reference somehow ended up in history

**Comment by awskii** [comment]
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getProof","params":["0xa2d37135730df5ada5da7fcaecfbf540271ed3c9",[],"0x7a1b0"],"id":1}' http://localhost:8545 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6786    0  6669  100   117  1246k  22400 --:--:-- --:--:-- --:--:-- 1325k
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "address": "0xa2d37135730df5ada5da7fcaecfbf540271ed3c9",
    "accountProof": [
      "0xf90211a00c2a7ba0fad7044ff5a3f920aa1b3dac9538a628581dd84e161fc0bee04230e5a0a41feec00c8790cb24fbcbce90330dfccd8470fe2c994cd6d326311191eaab9aa0a2f2866c31f2f742160e3422e32a237f2f5057b7da1113b75c29bd0d7085ea9ea063af80d4c56071d56ae4990c3f55b52e28eb65fd02d2e0d5f883147fdc3c59aba0f463420ba28b428e8a2831d57c2f3780a9553ddaa74072ab239ee3cbc32946d3a0adf4de43e4b9d58067ed24515ed93de5ec0c2daaeb4c3592eaf52a5e43d8fffca0377a54a3fba8ff81c2bae3f7e590ef772a85a27947b9734c7d74aa3c577c17d3a042d36a19bac5319c1c38ac5bf0391d4d3328764822170d364581658d79ab0e6aa028185cb8ed69fff7eff37557b3ed995cc36db028219d52aac15048c795eb3f90a071a22247005c6b69b5758711bc815b63b2237162d7cd4021237e83b17d0f76dea0ac40b3a9b81c20a4eaf2e196479a5a18b6f95ba8ba4ced87aba278046e0dadeaa0e4b7106cf48040f99dfee16987d7fc1e96526b6cc1c2936a5142eae00fd59a56a07380b9391aa634487543e461ccdee353cb8a74d7bfec743d266102221d637c6ca0c7192406dbaa99cd7abd30d76e476e2bb83dae7bb731d47c17fc5d19c74f0aa6a0f04b7e15473e46d35084c7febe2df6f15f669b16903cac41a4c553ea8aea3e38a08ceca63a00814c8bc54bcc89773729a85b8a23590563295327afc47ac6e1984480",
      "0xf90211a0f485f0becf5bbb6245dcb6be3991c0785e7fbf77413a7bd53fcbdc37f1b72eeaa0da84c85c807b99861ae50b3a9d07af7b9e5c8f3848b7bd712d3d47a66c1e8350a099ef26880522273338b639199242f4ce674a3e77eb50dd5c6156ea8297ca398ea08eeffd9a9c1a8556116477884065c0773bd4d2dab561c9635d80995ee3e9fce6a070200ed24cb25723057fa2c34c9c44c85cfe606a7df9da02eefb91424adec939a05ebc966d05ae0857fdc712cc2b10ca4c8baa64da336de322376ff1271c70446ba0259c44d71c0b2577f2c42bc7be80b05a3b8e3cfe2b4eb98496f0d3b3ebd58c16a094920d451eb61df99a53046aa9f3f92a5b4d6797d40f81680991dc58445e337aa0e784b97bc527dd1c36fd7c0953caee80e6f30e7a8f98e6ee7ff1f1485fd6f3c1a010bfeae5ee97378e87db201ff073607dd86d066805cbcc43a2f2fd68df81e1b7a0f98440ee3c65a9bba5b86c07a4abef3b4ca161b0739ba5f838b4f8e76ec29f83a082a68ecdc1786819e4c2fa6155588ce5426d18f10189a6bf129a96009b5b931ea0b2b7aa8d1f0dd948de16904c74a1f790aa70e3cd6faa5caa78ce919449f03f57a04f608373720d30f932974588eb61f37f9afbb3323d2f8217ca06f87827488e72a096207cc093989dec4cb6a7ce18f2abf00e3a01f94988b09cadfd5ff2f0876424a0aaa745b6c474322ea33f64a1cbc72f4be736257f740c93f5875ae9fc5ce5a72e80",
      "0xf90211a034cb3f8f93726e9976e43c57e5b5c6457f85456476c598f65be82cdd2f8ecb66a0dd02c5977bc68c82635bb3346c8f7b49712149ce3506c616d22f922d76fc3ebca0fba8b1ab7295009060e6e16aa667d45c0d9528bbcde3097fc923a7a9039b7338a095b9e42ba7ea409645d4f872e68755b6895a0786a95961c7f35d87c1856d2baaa0df4042db8a6a1124f4bd6717e0b5faff550224818af8d57b840a9bac6db3a3aba019a894ed6bb73f5ef9dec14573338d927480fc8becaf86dc396dfae658d63c3fa0fea3eca91b49e87be56451c20c3e16775b9ebd5004162e24941b57d40258d20ca0d228c4309d5183b1e11147231c4697dec7383734976483e4d69a8eed671fe267a01d0725c7481dd4f533320388407761844ac13fda1f570b4aa3ec24d5b0638e45a0ac96d41e56c6b6d50e2280c87d4bcd070a9697c22502445c9d3b3c574a405006a0f357c54cc3d14c30f99874b1b28232e4145ceb32921be882e003f8560f7a6ccba09d445dec5e0dbbd93f55476d188ddabbddb784a336ac3d2a21b945c108528ca5a035fd7703ecdc76a80e6c6454bb6b0529765b296c74922048b390ae9d2c64d74ca068aa525cb391cd7f50a76906062a06de569ac98025768cddd1dea488bca3c310a0f3f623d0dd8716e501e94dbea3b10b6339c6872532dca778169e1791e9982459a0d9e13ee585e2e07428a3345afdbf22b4f7664344a73baa3a7d82a2c958dd469180",
      "0xf90211a05acfcbe5e04d7a83a93fd54a2e602d51d0153b10baec0ed793c052a0404b3c58a0bfac8767b1f10ff39888437b908bc8d9894eeb416f6a5080231bcbff3435bcfaa0b5c49c43a12030b8fe30769465cc9510a629be081d21b10b9f5d4b99499d0d36a03b8267604f33f1f91f7bc217cecea148ad772ed99ec8f38b972bb7331933bdbda03f20206d10a17793f3962968b63dae98ef6fac355e10af580d5a8f7180c04d2aa0927c1188d83bb7a8173d4b519dc181fc9b7583587c0418c9dd397b69b27d4e22a0d862ee92b5c51d42cf4d5188915d597a11d7f6fdcf155022d31fcf093fc1388ea04194e45db58187e15647fa155226c64fd0b9853c0943e181b6958d2c92d237fca03cd52fe694c5e29c5529c66e163856d20f96e4ef7123d19c15a4c1425138e671a06875de03b82e291f744b0b6274586a3fc9fe28fefcad2d158653973a3c8a4e0aa09b5ce0097cefdae2b4b866e26dd32304b2101fc0355d0b720a0b7bd07a8ce9c7a0bc544d9eff4bdac970b02fc8a879263a1039ad09957d58b6a65676a99296a6d2a0b8a78e5b43ee317f8b1574aa8e1ff222511a43bb0a78dbda8ef0a6061446b5dba059d7beed58044c588d70f59b125f0c8597d325d41db86bb6a76cdd6624b05dcea09562a09be0fdcfbb93ce54bfe82ded1ff4eb8446136c2d39163fe4565aff0d11a00595ebe41d3184ba53c8543e6dfad81ec4206dcb4ff357a89f21d93a9786550c80",
      "0xf90211a0fd0989f5a49879dcb6c5d655d614bfd5d18b2aa50faf524a5774742800e303d4a00cc7b867e7ebe968e7564606c7ceca226d2608bf5b8548c59431f473c12bdd05a07e96b241054b4d957bd54f341cb9495654446498faa9af19112900c2e61aa1c6a02efc92c6cc98696625896e6e4cf67805cc0fbf2af088d34ed01f7efd90cb194fa0ea71295f4306f3059ee03109d15293a697894daf4b8019e547415557a0db0d2fa05fda38f1d909c246afc944cb9b650ae84cfc22f53a3b89394b68712a01053859a0ec08fb5b77657d25434605b9e97a5f3d38fca50fa8c0a646818633ac9191fd6fa0b138dba0aa37c0da94021eac11c2cb4dbf3b4abba70b9013500d846e986e016da0cc202e9014f8e0f088dce268b84632a08f040b57e6458eb22a68083b769d7f41a0e57909ba4b9f69bd287413a26c64cac925a031c95feb3502f331ea4a7124de40a00c0edd2cc43c8c5de5a488d14109bfcb5051e0c7573d8b0f74b6eddfa924805ea02129731d86915eef1a3c1127faf5212182154e91fca8551b6538b1538cbd86eda08d820f3c4e1c0bb69684bcc459e2c7659af9a154d47474990fc6165c4e70e9ffa0e65083eb9face7a1a036ef27458717b2532b2187d4ac3426c655c5e78efd29f3a0e5c37f8a67fa099f79f8ed78ee8848aad0450f8bc1cec47beb3ee9e46cb2910aa0cad7474b9cc744dbcbd0aae78265e6acb17bc6306a82117913f7c85050e1d6a380",
      "0xf90131a056a9cde76bce64ce16a283cf8e8c0a23fddda90699fb79f079c3ee91a464b5caa091d2f526c517b47538f2b45d29ac788ee22900b6907f08fc4570674e1054a2f080808080a058163f7d5663a42c70fe0666933d6242a0c7c5deb0c68521acf1e81bad154b4d80a082091c453e297599ee9089b277b2cc5ba0c2c16a4f6a6905c37cb047a602c25ea0765c276675a545e2a29808bce0073753d2a77025747cb14a873c7bbfb83aec8ba0a1594b0dde3e69f4e53148896e7c680e8e6ecbbfc0efaefd9ac2bd7d85862a25a0c7ad44533ea12c403a66b112219eb3a702bb126f2f6d74487363354360724044a0e321134ec1d64c473e74f5948410a6289b11dd565ee942ea737fc8806343f0d98080a0acf6ff85e9c0f4d02b141b1c5ed3de429a84050adf0439c0df177424d58416df80",
      "0xf85180a0782501cf0f5d210ffb55e26c196393299f0c2f253bc0b6c41cd7462b3940439b80a00a9a4b222c61bbbfb69c32e6309d820c44bb048b5d18bba24da149049c1e7edb80808080808080808080808080",
      "0xf8669d3cbcb7b46f9216e48ac2ca954a2c22b3842b299fb18b550688bd2539eeb846f8440280a04717ec79e817a54145942128d9402f8adc0fbcc32c95d7a9b16fc2a483f0cef9a0333f54fae451c70da63e254787d6325ce363e8f0d88abc0c4edf820bc488a00c"
    ],
    "balance": "0x0",
    "codeHash": "0x333f54fae451c70da63e254787d6325ce363e8f0d88abc0c4edf820bc488a00c",
    "nonce": "0x2",
    "storageHash": "0x4717ec79e817a54145942128d9402f8adc0fbcc32c95d7a9b16fc2a483f0cef9",
    "storageProof": []
  }
}
```

**Comment by awskii** [comment]
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getProof","params":["0x029d946f28f93399a5b0d09c879fc8c94e596aeb",[],"0x7a1a2"],"id":1}' http://localhost:8545 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7021    0  6904  100   117  1418k  24610 --:--:-- --:--:-- --:--:-- 1714k
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "address": "0x029d946f28f93399a5b0d09c879fc8c94e596aeb",
    "accountProof": [
      "0xf90211a06a2d5c04817b5d9452f27b2e94e5164164d85f2b27da9b70fe34fd2402c617dfa03bd7f411e9e7ac97b0315ada6776cd48882a3bd92e599fb690f43df64e341614a099397d875f93a365ed74c065062411adcc4ac384538c9e2a9eb7fcd724bf8caba0577f2f456e32b657701d574a091cb06d4793ab8b7292c3fd8af20f9fa3b181eea039cfd485d8cdffbfff9fd0f10e8c5f1fa3b7704035785ec564f956b46c2f1746a010450a1aa7a29f558a24753ed459b82d50ba3f33d1f1775c461569b0b58a90b2a0f904f3b02e227c7725a57fd092b6b7b194543a4bee113aafa18ce00080042771a0bad65bd276cd22a65453116070e448300ce703c9926abb5d47ee0125887ff0f5a04673a5a76d1417b1dd124f8a91b09f77a6ced1d3065792bbd2baee9ade6d9cf2a071a22247005c6b69b5758711bc815b63b2237162d7cd4021237e83b17d0f76dea09545e92db2c437bc2088c23d7ab378d824cda905a8ed9c98506d4f5bdb5456eba0db9905287c1ccf2db22ccd33bda296e3fc09e7465c8b4af31867b6c959d6366aa0dcb70fa9f4d7485ade2f37c5c385786667da37484590d3e9ffef33075bc73c25a00824a9224dd65b0b8b1aaec64d0cf80926e29c182a97b18f8659246021c5ef7da03a3535ed3ae4820935ec87c06bde89062997a0d22801f92f70c2d0ca363c1c34a0f6f0620dc34475047878395634d1f25472da1ddd3e503d0049cada99962606f280",
      "0xf90211a0e0c1e1b9f6b8827396966c993949dce04cfc1dfa408534ce0ebdda93ef16a3fea0695964ed53938e96168fbb353973cebba2e1b753b3d5d8a04a56ce9e569568d3a06532e4accb29457f838da533a429aa56f7f96366f44aa7744a756975977f82fba0aafb53fcb3f56a0c13d961931f9620c933ca6f271d8102a066af4248afcd256da0ab6ef21941e394a805d73b8ccdb7c21096dd9326b3639d0677846317a59f4cafa09b747a7776c716026befe67f67cfcc95180d08802ba9e1f5068251248c1265aba082b6a9a3c70f61895732b9fc53b99811e170680d35a0b5faa003a627b0202e38a0b17916b83594591154bb24b9742f381ecd60a65249e458962d407381faa83220a03576e2b15e4f9920aff15684fefa068380036421c212f05e3f4bc2eee5b6c108a00afed9bc1b64b3b62ca684a78f3d55f1d2a998d6afb462b4d1f0b7336f000cdea041b1c00a80a89f5b42dbbd0ad28fa371c83b9455ca3d2bc4d8b985f8ea7268e4a01d3caccbca737099ba4bc0ba8bed3cbce40436c9950b22bace50ab4be38da9d9a03b1fa7abc8115b59005e737c0791f6612056f257f3dc55f547c5dbe8e6d06422a098b1ea8037e7450d15dcd452028145effbfa3e069339a3950eee4e79ffbb0255a08099ac0c0039bb31e72cee213f29baef8e8ab6ef5d6d334f4b09de5086e36a92a0cf3a78c576850d202a90a985e3e9cc82909a4116ca46b6a031139992b38fb74880",
      "0xf90211a06548008c551d9127f0314220a1b67b7b7679e356b4e0a5f9c6bd58f6ad8ef0b7a0f9b7e9a6e56833cd3388a24140d27887d5a3b0f5cf7ea2930ec42b04c1333cd9a0025475202b370e2b89d9b7f49b6d040c94f903fe88f520c1e0fbe2bb42750016a0c6cd1c82a1aafd4a3ba86e6857c7922136f580b3540aee7a6553d9042436db58a0882933d1944019aa4d4990fa5ac8a10dea378548cb277c3318a7ac38874182f6a0b5fb63ec763ab856924f2468eb116c4083074d519da39e141e4546deecd17b04a09b33ac8ad575f9dbb52a19b7ad5749a85e5bb85e15acf243d24f3004034da8afa0eeb6aff72e285f2517e1e335f8f675975588fcfcae8f01726e6ca0b9cbf8a964a0bc8ac25d1a3938c060c242d141663621d1c61f49292086c63eee0bd1cc036981a03ebec4987d8ff72f179f9ab117a3cac6a3d071fb8e6d89547b58555ce10d3523a0d81a160730ea19182efd0d5e12b59d28dd3fab6fd59305633b4a62d2f5d890d7a049e53717e56a5923be0fbd8aa3506efd3470eb467de2631e5e742906346d533ca0665b8862268f47cb573c98e7e5ffe2e9b44e068221e1a82d229d546ee50c03e4a0f34aa5f11192d610b7b026e260b06fedb09e12557cb83ee88caa6f146cb7fca1a07f4e1e9a27ba8e4590730f7ef7ddac8916ce988ab3a3b94f330cd82bcbb0876aa0e1aee241687101b7b1c702916f4ee7f07f704d9d1e9ece7c3a5c140d6fd45d2d80",
      "0xf90211a063523c3311e11efb252a951d0ec7c0e0b7fa75bf05c15d7704d20838d5a08074a0eed9ae2995fbb3917f42018ebf7abcc53b79881fec7a1fe60e0c45d258af9fafa06901604b147b26ff2d285165a181de13a5ebc7714dec55d2f41891848e0a5b90a0cf37eea5dfef1bc7a5eb9bbe2665562d199319d5c99e38fbe3b7b342f92deee7a0d6a14bd0fada18fe931c345f59338c16f7ed99e76f45866e79c20c11a0e87fdaa0d16c44e12ce8bbc9c06726ad46bcc04299d75b76ed9203d70edfa805d2028c79a0ff679d1e3203a5e14582743c5627a99db3634fd022f2fd61850f683fcf4dbde5a075fe6623702a0514ace665130d6ae9b17ff50904d0069a9e247f905d36a4882da0bd3cae95f1bd0998ac1b2c79acdc6660e7e7fa908e7f829eaaf9b3825ce8c827a08b1bcb5ab90b2b2f49d11f67c9d11a11cd51049735aa9ca4203d35a5164bf4f4a07cfcc7df74bc61a05617573feefd06ff22d65ac3a3019228f6dc199ac77984faa0dc03ff58a9ae6e81f28fe71891af0bc9681d24b958781c4b7a79299198000b93a0e1b20bb08d3ea57a6c58cb0ba80acccf7507a20f30db548960a0ed15266b627aa0925492f744f3684f8dac37303e147f145a977ea5ae04a3cb786a0ca19dc7ce5da04c80610397b3f78c8372c36c8e5643f28f431901ac199a06cafdde0713d2be77a045dedc7459c662684bbbf54bb4766447213813d4fc8018029cdd2f734cfc340a80",
      "0xf90211a0ec4b9649d79a8a5f2fffd5c0eb726a52435cd94b7ed614334f34af61a19ffb65a0e69374a665493ac3c6b715e0c359b25d71acfe26add270a941b46cb93f62ec9ea0b28daf74b04fbf2d224ddadef1678b375380fedab2340b7673065b1e6c5339c2a09dcb46d5a47d273176ff77b32d8fb058a97349681d61856857b155d6060b7333a07761e2791f9cb882360bfb3ee65979e9e2b78f3d3b467bff107429f719b47826a0f908985e92fb4db01375841b00b167a5149e3e66001b462108c9ffd0c9a66565a07147627aa349751338257e5c631736666e425f5e74b8f7af0fd171644069db24a0ed30c8029d9537972285d94b53e8d0b51fd1f56005baba80eae236cb942018fba08e37da39411f31893e13c64a551467e49b951e3dd6a36278c7fdcc70b7b0fe46a050029e786a274a00f06abc02ce681318ec05ea75627cd0adab97fa79e7615fb5a05b310b0f4336e10897c56271ccbe4aa311b125b16437cd7884d416a18738b8e8a0187bf1d24532a9176ab366c36180a0fe63fb257da27ec894b9e35db38520c17ca0a9dc7d14a03e0c7e6e35fdddff3df01cc86e7af2f672b0ec8cf8c8f3f206f85da03c81de5d9ed7cabc844e9c21e9b2a741c4a1079fda9e8b5e28cd2081bc05f98ba08222b0a16928132cc2d1b407d4b91f6ed18339e59816e94635d1811f69f6e63ca08be6112343b94c6cbbd0bae8018a4f0473bf717afbf972d2899f3bf5c4b1f89c80",
      "0xf9013180a096f12f5eb5b82c89cea2ea641991b18995c7e7c89a4b4b806516c05343cff5a1808080a05904dab867dab96c2e89a8f6e2587b5b7a5236e8c3585e2ad06dc4aca367f3fda0a5e48465dcf2e4c4c71233262f6caae52d147762a6aaa5f0ea085d0d00d6ce11a0e7acd729f879fbb02a5ec3be2655d4addb17d242c97e689318640fc9d405e454a0ad2d9bf209fc05fe069b01be52ae76f610fcdf4abaa02903fa9ff32ffa5df63f80a0b885205da4088f418b49b0211fd5b4aa4ac75f0241cb1a0ccc55ad03d4dc9667a0d4340e9334b32d9c7c7679a7596b386cdfd7d3e62d7b5ead680e5172c3c6583d80a04acb4100b2ac6727d17e4c9d7249efe1f95e2e350317c802c415a24a7c0bd79aa06c0385f8017ca73fa9c80e1ffe7e3f11e7a8068dffbf26835a737fbdae1844d88080",
      "0xf871808080a06aac2e4b198f887171f382a8e7de3773a02234a3f9a2841f83cf4f528dd2c81a80808080a0e45079ab41ccd1dbf5fdda418726d22d2a34e5e719a5324df3037c097eaff5e3808080a0cd41ae269e5381d3df1490b28e405527300d5456e15bd855b868d7b13c41ecbc80808080",
      "0xf8518080808080808080a0927901e42690f897948f468530adc80f05aea1a52241b0e00e23273841b2fdbc80808080a0a821906188b145488a51fb7ba281b5c96230e15a76d127780a574f958e6fb5c1808080",
      "0xf8669d2048b7465498ea8fe8df1d0a5c7b6e3b7add9c0c83b86c4e839330feafb846f8440180a04cab3a5dc88ac54b3cb389f7b35c1a0651ea0633e27a65d414830e91622f88a5a08ce39892f94791f1f2f2fcbb6ee0438c41b8cb53c40aeb4215a2a0111e88801e"
    ],
    "balance": "0x0",
    "codeHash": "0x8ce39892f94791f1f2f2fcbb6ee0438c41b8cb53c40aeb4215a2a0111e88801e",
    "nonce": "0x1",
    "storageHash": "0x4cab3a5dc88ac54b3cb389f7b35c1a0651ea0633e27a65d414830e91622f88a5",
    "storageProof": []
  }
}
```

**Comment by awskii** [comment]
https://github.com/erigontech/erigon/pull/16251
https://github.com/erigontech/erigon/pull/16564
https://github.com/erigontech/erigon/pull/16606
https://github.com/erigontech/erigon/pull/16687

Resolved

**Comment by antonis19** [comment]
These test cases are still failing in`main`, with `empty branch data` .

**Comment by antonis19** [comment]
This is now fixed as of release 3.3.0 .
